### PR TITLE
Pull my change please

### PR DESCRIPTION
**Pull request by zjrosen1**

### CODE REVIEW

**Comment by afeld** [comment]
Awesome, thanks, sorry I didn't see this during the presentation!

**Comment by zjrosen1** [comment]
Its all good, just trying to help out. Im the mentor who told you to show
some cool log stuff.

**Comment by afeld** [comment]
Ah, coolio.  Tried to give a taste, based on your suggestion.  More than happy to talk shop tomorrow!

**Comment by zjrosen1** [comment]
Im going to be teaching a course on vim and using git inside vim with
fugitive in downtown detroit next month. Would love to chat tommorow!

This was the refrence video I had mentioned earliar. Found it very useful
if your a hackathoner might come in handy for future presentations

https://m.youtube.com/watch?v=MYP56QJpDr4

**Comment by afeld** [comment]
Ha, nice.  Had been thinking about putting together a talk like that, actually... didn't know @tlberglund (who is on my team) had one already!

**Comment by zjrosen1** [comment]
I normally dont share 45 minute videos with my friends unless I think it is
absolutely worth it, he had a winner for sure.

**Pull request closed without merging**
